//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoiTap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoiTap()
        {
            this.ChiTietDK_GoiTap = new HashSet<ChiTietDK_GoiTap>();
        }
    
        public int id_GT { get; set; }
        public string TenGoiTap { get; set; }
        public Nullable<System.DateTime> ThoiGianHieuLuc { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDK_GoiTap> ChiTietDK_GoiTap { get; set; }
    }
}
